export default {
  linkHomePage: document.querySelector('.js-link-homepage'),
  linkLibrary: document.querySelector('.js-link-library'),
  homePage: document.querySelector('.js-home-section'),
  homePage1: document.querySelector('.js-link-homepage'),
  libraryPage: document.querySelector('.js-library-section'),
  linkLogo: document.querySelector('.logo'),
  libraryFilmList: document.querySelector('.js-library-filmlist'),
  watchedBtnLib: document.querySelector('.js-watchedBtnLib'),
  queueBtnLib: document.querySelector('.js-queueBtnLib'),
  btnContainer: document.querySelector('.btn-container'),
  nextBtn: document.querySelector('.btn-next'),
  nextHomeBtn: document.querySelector('.btn-next-home'),
  pageBtn: document.querySelector('.btn-number'),
  prevBtn: document.querySelector('.btn-prev'),
  prevHomeBtn: document.querySelector('.btn-prev-home'),
  moviesContainer: document.querySelector('.home-movie-list'),
  homePage: document.querySelector('#homePage'),
  searchForm: document.querySelector('#homePage__search'),
  inputForm: document.querySelector('#homePage__search-input'),
  popularPage: document.querySelector('.popular-movie-list'),
  detailsPage: document.querySelector('#detailsPage'),
  moviesContainer: document.querySelector('.main_filmlist'),
  libBtnList: document.querySelector('.libraryPage_list'),
};
